### ISSUE TITLE
OpenJfx with OpenWebstart throws Exception

### ISSUE THREAD

**Issue by AM-Xdev** [karakun/OpenWebStart#125] opened 2019-12-10 09:35 UTC
Hi we use OpenWebstart to start an application which uses basically swing but JavaFx for the buildin Browser.
So the App starts but when we get to the part where the JavaFxBrowser will be used, we get the follwing Error:
```
  at java.base/java.lang.Thread.run(Thread.java:834) 
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) 
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) 
    at com.sun.glass.ui.Application.lambda$run$1(Application.java:153) 
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(QuantumToolkit.java:258) 
    at com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(QuantumToolkit.java:313) 
    at com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(QuantumToolkit.java:695) 
    at com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(D3DPipeline.java:205) 
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException 
    at java.base/java.lang.Thread.run(Thread.java:834) 
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) 
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) 
    at com.sun.glass.ui.Application.lambda$run$1(Application.java:152) 
    at com.sun.glass.ui.Screen.initScreens(Screen.java:412) 
    at com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method) 
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init> 
    at java.base/java.lang.Thread.run(Thread.java:834) 
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) 
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) 
    at com.sun.glass.ui.Application.lambda$run$1(Application.java:152) 
    at com.sun.glass.ui.Screen.initScreens(Screen.java:412) 
    at com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method) 
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
```

We have tried to add the exports for the com.sun-packages to the JNLP but that is not helping:
```
 --add-exports=javafx.graphics/com.sun.glass.ui.win=ALL-UNNAMED,ALL-SYSTEM,java.base
 --add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED,ALL-SYSTEM,java.base
```

So our 2 Main Questions are:
1. If we want to use the ModuleSystem where we have to put the exports etc.
2. It is possible to run WebstartApplications in Classpath-Mode, because if we start our app from Commandline all works fine.

**Comment by sclassen** [comment] 2019-12-10 09:46
OpenWebStart is a JNLP client. As such it dates back to 2002 and Java 1.4.
So sorry there is no support for Java9 module system.
Everything is passed to a custom class loader which will treat all sources as if they are on the class path

**Comment by AM-Xdev** [comment] 2019-12-10 10:10
This is good to hear, because we doenst want to use modules at the moment, but why it doesnt work on webstart but on commandline.

**Comment by AM-Xdev** [comment] 2019-12-11 13:57
I've build an Demoproject:
[openwebstart-openfx-test.zip](https://github.com/karakun/OpenWebStart/files/3950627/openwebstart-openfx-test.zip)
Requirements: Jdk 11, maven 3.5+, openwebstart 1.0.0

- Unzip
- run mvn clean package -P deployment
- unzip /target/openwebstart-openfx-test-0.0.1-SNAPSHOT.zip to an localhost webserver of your choice.
- open Openwebstart-OpenFx-Test.jnlp the the Error Above
- open openfx-classpath-start.cmd : 
![2019-12-11_14h56_49](https://user-images.githubusercontent.com/40858279/70627410-7970ec00-1c26-11ea-89fb-b22a7660283f.png)

**Comment by DaveDevelop** [comment] 2019-12-11 21:26
JavaFX is not only some jars but also native DLLs (so/dylib for linux/mac)
I recently got it working by taking all the JavaFX dlls zipping them into a Jar
I had to include a Manifest and sign the jar, but our whole application is signed, so I don't know if this is required
Then included it as a Native Lib in my JNLP, if you support multiple OS, you need to do this for each OS

`<j2se version="1.8+" href="http://java.sun.com/products/autodl/j2se" />    `        
`<j2se version="11+" >`
`         <resources os="Windows" >`
`                <jar href="Client/lib/resources/windows/javafx.base.jar"  />`
`                <jar href="Client/lib/resources/windows/javafx.controls.jar"  />`
`                <jar href="Client/lib/resources/windows/javafx.fxml.jar"  />`
`                <jar href="Client/lib/resources/windows/javafx.graphics.jar"  />`
`                <jar href="Client/lib/resources/windows/javafx.media.jar"  />`
`                <jar href="Client/lib/resources/windows/javafx.swing.jar"  />`
`                <jar href="Client/lib/resources/windows/javafx.web.jar"  />`
`                <jar href="Client/lib/resources/windows/javafx-swt.jar"  />`
`                <nativelib href="Client/lib/resources/windows/javafx_bin.jar"/>`
`          </resources>`
`          <resources os="Linux" >`
`                <jar href="Client/lib/resources/linux/javafx.base.jar"  />`
`                <jar href="Client/lib/resources/linux/javafx.controls.jar"  />`
`                <jar href="Client/lib/resources/linux/javafx.fxml.jar"  />`
`                <jar href="Client/lib/resources/linux/javafx.graphics.jar"  />`
`                <jar href="Client/lib/resources/linux/javafx.media.jar"  />`
`                <jar href="Client/lib/resources/linux/javafx.swing.jar"  />`
`                <jar href="Client/lib/resources/linux/javafx.web.jar"  />`
`                <jar href="Client/lib/resources/linux/javafx-swt.jar"  />`
`                <nativelib href="Client/lib/resources/linux/javafx_bin.jar"/>`
`          </resources>`
`          <resources os="Mac\ OS\ X" >`
`                <jar href="Client/lib/resources/mac/javafx.base.jar"  />`
`                <jar href="Client/lib/resources/mac/javafx.controls.jar"  />`
`                <jar href="Client/lib/resources/mac/javafx.fxml.jar"  />`
`                <jar href="Client/lib/resources/mac/javafx.graphics.jar"  />`
`                <jar href="Client/lib/resources/mac/javafx.media.jar"  />`
`                <jar href="Client/lib/resources/mac/javafx.swing.jar"  />`
`                <jar href="Client/lib/resources/mac/javafx.web.jar"  />`
`                <jar href="Client/lib/resources/mac/javafx-swt.jar"  />`
`                <nativelib href="Client/lib/resources/mac/javafx_bin.jar"/>`
`          </resources>`
`</j2se>`

**Comment by AM-Xdev** [comment] 2019-12-12 09:55
I've tried it with the Demo-App but both of my solution doesnt work:
1. mark all javafx-Libs which contains dll as native.
```
 <jar href="openwebstart-openfx-test-0.0.1-SNAPSHOT.jar" main="true"/>
    <jar href="javafx-controls-11.jar"/>
    <jar href="javafx-controls-11-win.jar"/>
    <jar href="javafx-graphics-11.jar"/>
    <nativelib href="javafx-graphics-11-win.jar"/>
    <jar href="javafx-base-11.jar"/>
    <jar href="javafx-base-11-win.jar"/>
    <jar href="javafx-swing-11.jar"/>
    <jar href="javafx-swing-11-win.jar"/>
    <jar href="javafx-web-11.jar"/>
    <nativelib href="javafx-web-11-win.jar"/>
    <jar href="javafx-media-11.jar"/>
    <nativelib href="javafx-media-11-win.jar"/>
```
2. delete all DLL's from the maven libs, build ONE DLL-Lib and mark that as native.
```
  <jar href="openwebstart-openfx-test-0.0.1-SNAPSHOT.jar" main="true"/>
    <jar href="javafx-controls-11.jar"/>
    <jar href="javafx-controls-11-win.jar"/>
    <jar href="javafx-graphics-11.jar"/>
    <jar href="javafx-graphics-11-win.jar"/>
    <jar href="javafx-base-11.jar"/>
    <jar href="javafx-base-11-win.jar"/>
    <jar href="javafx-swing-11.jar"/>
    <jar href="javafx-swing-11-win.jar"/>
    <jar href="javafx-web-11.jar"/>
    <jar href="javafx-web-11-win.jar"/>
    <jar href="javafx-media-11.jar"/>
    <jar href="javafx-media-11-win.jar"/>
    <nativelib href="windows-nativ-11.jar" /
```

**Comment by rafik777** [comment] 2019-12-12 15:35
@AM-Xdev You can use Liberica JDK which has bundled javafx for all versions.
We use openwebstart with companion of Liberica JDK from Bellsoft
https://bell-sw.com/

**Comment by DaveDevelop** [comment] 2019-12-13 03:01
Is it still throwing the same error?
I had one PC where I needed to uninstall Java 8 from windows.
I had done a google, and it appears the JVM (11) may pickup the dll from the installed jvm (8) instead of the nativelib

**Comment by hendrikebbers** [comment] 2019-12-13 10:44
@AM-Xdev can you please attach the log files of OpenWebStart (with activated debug logging)

**Comment by AM-Xdev** [comment] 2019-12-13 15:29
@DaveDevelop 
You are right after uninstall Java 8 it works, when I'm using all DLL's in an separate Jar tag as Nativejar.
But only with my DemoApp.

With our real App I have with Openwebstart 1.0.0 
this error:
```
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:669)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:411)
	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:756)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Application Error: The JNLP application is not fully signed by a single cert. The JNLP application has its components individually signed, however there must be a common signer to all entries.
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$SecurityDelegateImpl.getClassLoaderSecurity(JNLPClassLoader.java:2215)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.setSecurity(JNLPClassLoader.java:384)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:671)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:347)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:492)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:465)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:661)
	... 3 more
```
And with Openwebstart 1.1.0
I've got the Error from 
https://github.com/karakun/OpenWebStart/issues/124
And for that Issue I'll make a full Log an Monday.

**Comment by deamn** [comment] 2020-01-23 10:28
If you add into your jnlp file this: `<property name="java.library.path" value="C:/"/>` your application will start. Please see [this](https://stackoverflow.com/questions/52906570/javafx-11-using-maven-throws-exception-windowsnativerunloopthread). You have on windows path a jre or jdk that expose glass.dll and the jvm use this dll instead of the included dll

**Comment by hendrikebbers** [comment] 2020-06-02 08:54
THX @deamn for pointing me to this windows dll issue :)

Looks like this is really the problem behind the bug. When you start a JNLP file that contains JFX11+ Jars on windows by double-click you will / might end in the `java.lang.NoSuchMethodError` that is described in the first post of this issue. By using the [Windows Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) we analysed the java process and received a list of all used DLLs. In the attached image you can see that the `glass.dll` is coming from the old Oracle Java 8 runtime that is installed on the system. 
<img width="972" alt="dll" src="https://user-images.githubusercontent.com/9443847/83500285-d99e6780-a4be-11ea-9108-b5b937e8295a.png">
This might be based on a bad value in the `java.library.path` property as described [in an eclipse bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=540247) and [the javafx mailing list](https://openjfx-dev.openjdk.java.narkive.com/IRNmXOM2/running-javafx-11-applications-from-within-eclipse-fails).

Further investigation needed. cc @janakmulani

**Comment by hendrikebbers** [comment] 2020-06-05 07:33
I submitted a Bug report to OpenJDK. Will update this issue once I have news.
For now the only fix will be to install a locally installed JRE or remove it from the path.

Same issue at Stackoverflow: https://stackoverflow.com/questions/52906570/javafx-11-using-maven-throws-exception-windowsnativerunloopthread

**Comment by hendrikebbers** [comment] 2020-06-16 11:08
Issue in Java issue tracker: https://bugs.openjdk.java.net/browse/JDK-8246796

**Comment by hendrikebbers** [comment] 2020-06-16 12:47
I tried this on another windows machine with an installed Oracle Java 8. Even by having the `bin` folder of the JRE on the `PATH` everything worked fine. Instead of loading the `glass.dll` from the `bin` folder of the locally installed JRE Java loaded a glass.dll that was located under `USER_HOME/.openjf/cache` as you can see in the following image:
![pasted_image](https://user-images.githubusercontent.com/9443847/84775523-9fb18300-afdf-11ea-8b3a-05eb6d149888.png)

Looks like on this Machine javaFX creates a cached folder that contains all native libraries (dll files). The following picture shows how the content of such folder looks:

![pasted_image-2](https://user-images.githubusercontent.com/9443847/84775655-c53e8c80-afdf-11ea-85fa-35e9cf25b021.png)

Based on this I had another look at the JavaFX sources and found `com.sun.glass.utils. NativeLibLoader` that does some magic here ([link](https://github.com/javafxports/openjdk-jfx/blob/a42b5841674ab7cd2704e0ea5fbcc94934d91c83/modules/javafx.graphics/src/main/java/com/sun/glass/utils/NativeLibLoader.java#L43)). Additional information can be found [here](https://stackoverflow.com/questions/53382810/configure-openjfx-11-to-extract-its-dlls-into-a-different-user-specified-directo).

@janakmulani Can you please set `javafx.verbose` to `true` and check if you have a `USER_HOME/.openjf/cache` folder. Next to this we can try to modify the folder by defining `javafx.cachedir`. I assume that we can find some more information based on this new input. @AM-Xdev can you have a look at your setup, too?

**Comment by hendrikebbers** [comment] 2020-06-16 13:04
INFO: The last test was not done by using OpenWebStart. We started a JavaFX application that was created by `jlink`. Maybe this already makes a different.

**Comment by hendrikebbers** [comment] 2020-06-16 13:19
more info for native lib loading on win: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

**Comment by janakmulani** [comment] 2020-06-17 06:46
> 
> 
> I tried this on another windows machine with an installed Oracle Java 8. Even by having the `bin` folder of the JRE on the `PATH` everything worked fine. Instead of loading the `glass.dll` from the `bin` folder of the locally installed JRE Java loaded a glass.dll that was located under `USER_HOME/.openjf/cache` as you can see in the following image:
> ![pasted_image](https://user-images.githubusercontent.com/9443847/84775523-9fb18300-afdf-11ea-8b3a-05eb6d149888.png)
> 
> Looks like on this Machine javaFX creates a cached folder that contains all native libraries (dll files). The following picture shows how the content of such folder looks:
> 
> ![pasted_image-2](https://user-images.githubusercontent.com/9443847/84775655-c53e8c80-afdf-11ea-85fa-35e9cf25b021.png)
> 
> Based on this I had another look at the JavaFX sources and found `com.sun.glass.utils. NativeLibLoader` that does some magic here ([link](https://github.com/javafxports/openjdk-jfx/blob/a42b5841674ab7cd2704e0ea5fbcc94934d91c83/modules/javafx.graphics/src/main/java/com/sun/glass/utils/NativeLibLoader.java#L43)). Additional information can be found [here](https://stackoverflow.com/questions/53382810/configure-openjfx-11-to-extract-its-dlls-into-a-different-user-specified-directo).
> 
> @janakmulani Can you please set `javafx.verbose` to `true` and check if you have a `USER_HOME/.openjf/cache` folder. Next to this we can try to modify the folder by defining `javafx.cachedir`. I assume that we can find some more information based on this new input. 

@hendrikebbers  To make OWS run on dbl clk on jnlp file of JFX app, I removed my installation of JRE8 so that its bin was removed from the path. After that my app runs. If you remember OWS and JFX app jnlp was working  OK if started from command line.

I do have `USER_HOME/.openjf/cache` folder. It contains directories with OpenJFX version numbers and respective dlls in it.

BTW I saw this :  
https://github.com/gluonhq/client-gradle-plugin/issues/39 
https://stackoverflow.com/questions/53382810/configure-openjfx-11-to-extract-its-dlls-into-a-different-user-specified-directo

**Comment by AM-Xdev** [comment] 2020-06-17 14:02
> @AM-Xdev can you have a look at your setup, too?
yes on my Computer i have this `USER_HOME/.openjf/cache` folder, with my version 13.0.2.

**Comment by hendrikebbers** [comment] 2020-06-18 15:55
@AM-Xdev you are using windows, right? Can you please check by using Windows Process Explorer what glass.dll is used for the JavaFX app?

**Comment by AM-Xdev** [comment] 2020-06-19 08:34
> 
> 
> @AM-Xdev you are using windows, right? Can you please check by using Windows Process Explorer what glass.dll is used for the JavaFX app?

Yes I'm using Windows and with both ways using glass.dll from .openjf/cache:

- Starting JavaFX from cmd: 
![2020-06-19_10h06_43](https://user-images.githubusercontent.com/40858279/85113872-47b19100-b218-11ea-912b-51fa08b7211b.png)

- And starting with OpenWebstart 1.1.8  
![2020-06-19_10h29_51](https://user-images.githubusercontent.com/40858279/85113965-6fa0f480-b218-11ea-805f-5210ecee58b0.png)

**Comment by hendrikebbers** [comment] 2020-06-26 07:12
Another Java bug I created: https://bugs.openjdk.java.net/browse/JDK-8248122

**Comment by hendrikebbers** [comment] 2020-07-22 08:49
I had a call with @AM-Xdev and now understand the general problem. Looks like the JavaFX WebView is not working correctly. @AM-Xdev will upload an "Hello-World"-Sample and a DLL overview created by Windows Process Explorer. @janakmulani we should schedule a chat the next days to have a look.

**Comment by janakmulani** [comment] 2020-07-22 10:07
@hendrikebbers Sure we can have a look together. I already have a sample with WebView. However, the problem occurs even for a simple Hello World that does not use WebView.

**Comment by AM-Xdev** [comment] 2020-07-22 11:17
Here is the Demo Projekt
[openwebstart-openfx-13-test.zip](https://github.com/karakun/OpenWebStart/files/4959638/openwebstart-openfx-13-test.zip)

Unzip
run "mvn clean package -P deployment"
unzip /target/openwebstart-openfx-test-0.0.1-SNAPSHOT.zip to an localhost webserver of your choice.
open Openwebstart-OpenFx-Test.jnlp : App crashes without any hint.
open openfx-classpath-start.cmd : its working

the DLL-Logs looks like:
[DLL-Log-openwebstart-openfx-13-test.zip](https://github.com/karakun/OpenWebStart/files/4959651/DLL-Log-openwebstart-openfx-13-test.zip)

**Comment by hendrikebbers** [comment] 2020-07-23 07:19
We have a sample that use basic JavaFX controls (Button, etc.) and is more or less setup as your application. That sample is working fine. So maybe it is just the web view that makes problems here.

**Comment by janakmulani** [comment] 2020-07-24 06:19
I created a simple JavaFX app with WebView which just loads a Url. App comes up with OWS, page is loaded and shown in WebView and then after few seconds the app crashes. The same app works with java cmd. So yes there is something going on with WebView and OWS. We will investigate.

**Comment by janakmulani** [comment] 2020-07-24 06:19
I created a simple JavaFX app with WebView which just loads a Url. App comes up with OWS, page is loaded and shown in WebView and then after few seconds the app crashes. The same app works with java cmd. So yes there is something going on with WebView and OWS. We will investigate.

**Comment by hendrikebbers** [comment] 2020-07-28 09:54
Some similar issues about WebView problems:
https://jira.karakun.com/browse/OWS-450
https://github.com/javafxports/openjdk-jfx/issues/316
https://github.com/update4j/update4j/issues/83

**Comment by hendrikebbers** [comment] 2020-07-31 09:16
Some updates:

I did a small change in the Java class for the sample. The `createAndShowGUI()` method was called 2 times. Please update the sample with the given java class ;) 
[SwingOpenFxBrowser.java.zip](https://github.com/karakun/OpenWebStart/files/5006159/SwingOpenFxBrowser.java.zip)

Next to this we can say that we can not reproduce the error on Linux and MacOS. Based on the very good step by step documentation from @AM-Xdev we can start it on UNIX based systems without a problem. I attached a pic from the JNLP application on Mac.

<img width="612" alt="jnlp" src="https://user-images.githubusercontent.com/9443847/89020477-413a2d00-d31f-11ea-8f4f-1bb713fa8874.png">

We need to do further investigations on windows.

**Comment by sclassen** [comment] 2020-07-31 11:52
Also runs on Windows...

![image](https://user-images.githubusercontent.com/1795224/89032468-0f33c580-d335-11ea-8078-c70cbf9b460f.png)

**Comment by hendrikebbers** [comment] 2020-07-31 12:01
We need to do further testing to find why this works on some systems and fails on other systems. We can reproduce both. But since we can now reproduce it I think that we can discuss this next week and check how much time we will spend on this

**Comment by hendrikebbers** [comment] 2020-08-03 09:18
The issue is based on the used JVM. It looks like the error only happens when specific JVMs are used as runtime for the application. We will do some tests with different JVMs

**Comment by hendrikebbers** [comment] 2020-08-03 09:24
Error on Mac when using AdoptOpenJDK 11.x

[mac-error.log](https://github.com/karakun/OpenWebStart/files/5015015/mac-error.log)

<img width="1112" alt="mac" src="https://user-images.githubusercontent.com/9443847/89167258-75aa2500-d57b-11ea-97a2-f799892e0396.png">

**Comment by hendrikebbers** [comment] 2020-08-03 09:36
Related issues:

https://github.com/javafxports/openjdk-jfx/issues/316#issuecomment-457912843
https://github.com/update4j/update4j/issues/83
https://bugs.openjdk.java.net/browse/JDK-8196011

**Comment by hendrikebbers** [comment] 2020-08-03 10:50
It looks like the sample is only working with Azul Zulu with a bundled JavaFX. The JavaFX WebView has a bug that needs the WebView Jar to be loaded as a real Java module on the module path or as a lib in the bootclassloader. OpenWebStart does not provide any of the given Options.

Both Azul and Bellsoft provide JVMs with bundled JavaFX. The Azul Zulu JVM for example is provided by OpenWebStart per default. With Bellsoft the given solution does not work at the moment but we are talking with Bellsoft to get this fixed as fast as possible. Therefore Azul Zulu needs to be used for now.

We refactored the given JNLP file to work currently with a JVM that contains a bundled JavaFX:

```
<?xml version="1.0" encoding="UTF-8"?>
<jnlp spec="1.0+" codebase="http://localhost/" href="Openwebstart-OpenFx-Test.jnlp">
    <security>
        <all-permissions/>
    </security>
    <information>
        <title>openwebstart.SwingOpenFxBrowser</title>
        <homepage href="http://localhost/"/>
        <offline-allowed/>
    </information>
    <resources>
        <j2se version="11+">
        <resources>
            <jar href="openwebstart-openfx-test-0.0.1-SNAPSHOT.jar" main="true"/>
        </resources>
    </resources>
    <application-desc main-class="openwebstart.SwingOpenFxBrowser">
    </application-desc>
</jnlp>
```

Next to this OpenWebStart needs to be configured to only use the Zulu JVMs with embedded JavaFX to start the application. Details can be found in the documentation of OpenWebStart.

**Comment by hendrikebbers** [comment] 2020-08-19 08:18
Since this issue is related to JavaFX (see above) and using a JVM with embedded JFX is a valid workaround for @AM-Xdev  I close this issue.

**Closed by hendrikebbers** 2020-08-19 08:18 UTC
Labels: tracked internally

**Comment by janakmulani** [comment] 2021-09-03 13:43
> 
> 
> I created a simple JavaFX app with WebView which just loads a Url. App comes up with OWS, page is loaded and shown in WebView and then after few seconds the app crashes. The same app works with java cmd. So yes there is something going on with WebView and OWS. We will investigate.


OpenJfx v 17-ea+16-win has a fix for the problem of crashing of  app with JavavFX WebViiew when started with OWS.

However due to a bug in OWS  1.4.0 for now (till the issue is fixed) you need to rename the OpenJfx jars for example as follows:
javafx-base-17-ea+16-win.jar to javafx-base-17-win.jar
