### ISSUE TITLE
OpenWebStart installer for RHEL and CentOS

### ISSUE THREAD

**Issue by neelambatra** [karakun/OpenWebStart#310] opened 2020-08-19 07:06 UTC
Hello,
I am also looking for the Openwebstart installers/RPMs for RHEL and CentOS. I tried to convert the DEB package to RPM using alien but that failed. Has someone created RPM from DEB package successfully?

**Comment by sclassen** [comment] 2020-08-21 07:40
This is a duplicate of #154

**Closed by sclassen** 2020-08-21 07:40 UTC
