### ISSUE TITLE
OpenWebStart Cannot create shortcut on Desktop that is network share drive.

### ISSUE THREAD

**Issue by alslw** [karakun/OpenWebStart#381] opened 2021-01-20 09:47 UTC
Hi
We login test user (non-admin) and install OWS 1.2.1 on Win 10 (64bit) and we map network share drive to Desktop of test user and set permission "full control" on this network share drive for this user. When we try to use OWS launch our jar and create shortcut on Desktop that is network share drive by using jnlp file but it show some error "Can not create desktop entry for app"
<img width="699" alt="Cannot_create_ShortcutOnDesktop" src="https://user-images.githubusercontent.com/12932352/105156416-64ab9b00-5b3e-11eb-8001-c7d17b9de78b.png">

Would it limitation of OWS ?

**Comment by sclassen** [comment] 2021-01-21 09:46
Are you using OWS in a windows terminal environment?

**Comment by alslw** [comment] 2021-01-22 02:47
We use rdp program to login user that use roaming user profile to map network drive to Desktop of user.

**Comment by sclassen** [comment] 2021-01-26 22:46
the error comes directly from the file system.
Thus it is most likely e problem with the permissions of the user which executes OWS.

**Comment by alslw** [comment] 2021-01-27 02:47
Hi 
   We assign permission of this user to be "Full Control" and we login with this user and try to create file and folder on Desktop for testing permission of this user, we found it can create file and folder. Please see the result at the picture in below.
<img width="915" alt="test_permission_OnDesktop" src="https://user-images.githubusercontent.com/12932352/105935352-69170d00-6084-11eb-91f0-0aa3d1f91fac.png">

**Comment by sclassen** [comment] 2021-01-29 10:41
Since we cannot reproduce this on our environment we can only try to guide you in finding the solution.

Can you log out the system properties on the JavaConsole in OpenWebStart to see if `os.user` is set to the correct user.

**Comment by alslw** [comment] 2021-02-01 05:23
Hi 
We can reproduce this case by following these procedure on our test machine(Windows 10 for 64 bits) in below:
1. Create test user that is member of Users and "Remote Desktop Users" groups
<img width="436" alt="Create_test-user" src="https://user-images.githubusercontent.com/12932352/106416859-060ee700-6485-11eb-9081-ce3e132e0d5f.png">

2. Create share on our test machine by using share name "Desktop" on D:\Temp\Desktop directory and assigned permission of test user to be "Full Control"
<img width="526" alt="Create_ShareWithPermissionForTest-user" src="https://user-images.githubusercontent.com/12932352/106416883-145d0300-6485-11eb-8002-62ad7200cc25.png">

3. Create directory for Desktop of test user in D:\temp\Destop such as D:\temp\Destop\test\Desktop

4. Login test machine with test user in step 1 and right click on the Desktop folder, click Properties, Click Location tab and enter "\\\hostname of test machine\\[share name]\\[directory in step 3]"  
Note: This step require administrative right, then it will prompt for user and password of user that have administrative right to process.
<img width="551" alt="MapDesktop2ShareDrive" src="https://user-images.githubusercontent.com/12932352/106416925-322a6800-6485-11eb-825f-577b40604f1a.png">

5. Create Command prompt and go to directory that have OpenWebStart installer and install OpenWebstart with default setting.
Note: It will install OpenWebStart in C:\Users\test\AppData\local\OpenWebstart
6. Load jar from jnlp file by command "C:\Users\test\AppData\local\OpenWebstart\javaws.exe [Jnlp file]"
The Result: It can load jar file but it will show error when it try to create shortcut on C:\Users\test\Desktop directory that is not share drive of step 2. We try to access C:\Users\test\Desktop directory that show in this error but it is failed. Is it possible OWS cannot get Desktop directory that map to share drive, then get wrong location for Desktop directory ?
Normally, we can get this value from registry that you can use this command "reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v Desktop" to get it. See the picture in below.
<img width="870" alt="Error_WhenCreateShortcut" src="https://user-images.githubusercontent.com/12932352/106414469-3a7fa480-647f-11eb-8a3d-f567f02b3dba.png">

<img width="632" alt="Get_DesktopFromReg" src="https://user-images.githubusercontent.com/12932352/106418021-ed540080-6487-11eb-86b2-2dabdb901f5c.png">

**Comment by sclassen** [comment] 2021-02-01 05:33
Could this be the same issue as #243 ?

**Comment by sclassen** [comment] 2021-02-16 09:01
Closing this as #243 has been fixed. Please reopen if this still is an issue with v1.3.3 or greater

**Closed** 2021-02-16 09:02 UTC

**Comment by alslw** [comment] 2021-02-18 05:37
we don't see v1.3.3 to download in https://github.com/karakun/OpenWebStart/releases. When does this version release ?

**Comment by sclassen** [comment] 2021-02-18 08:21
1.3.3 is the upcomming bugfix it will be out soon. We recommend subscribing to the newsletter. We do not send advertisement or other unwanted mails. But you get notified about every release
https://openwebstart.com/subscribe/
