### ISSUE TITLE
Extreme slow startup of java spring swing application

### ISSUE THREAD

**Issue by AG72** [karakun/OpenWebStart#152] opened 2020-01-07 10:09 UTC
We are using a Java 8 Webstart application based on Spring and Swing since a long time. With Oracle webstart and Oracle or Zulu 8 it starts up in a second.

Now I tried with Zulu 8 and Openwebstart 1.1.1. It runs, but the startup takes **4 Minutes** from the moment on the splashscreen of our application shows up to the moment I can use the application.
During this time, there is high CPU load, lots of memory is used and the log file is messed up with the same message many times a second (neo-swing.jar is our application):

`2020-01-07 09:57:35,433 [null] [1.24.4.53] [35257] [07.01.2020 09:53:10] [SwingWorker-pool-3-thread-1] INFO  n.a.i.l.SystemOutLoggerFactory - Tue Jan 07 09:57:35 CET 2020 [DEBUG  ] net.sourceforge.jnlp.runtime.CachedJarFileCallback: Class-Path attribute cleared for C:\Users\myuser\.cache\icedtea-web\cache\0\90\neo-swing.jar `
See all messages in [openwebstart_startup_log.txt](https://github.com/karakun/OpenWebStart/files/4030016/openwebstart_startup_log.txt)

Is this possibly a bug as I would expect the same behaviour as with Oracle webstart, or anything I can change?

**Comment by hendrikebbers** [comment] 2020-01-07 11:20
can you add your JNLP file?

**Comment by AG72** [comment] 2020-01-07 12:14
Of course, here it is: 
[neoProd1.zip](https://github.com/karakun/OpenWebStart/files/4030547/neoProd1.zip)
Note that the resource version numbers in this .jnlp is always the version number of our relase. In fact we use Spring 4.0.5, Hibernate 4.3.8 etc.

Btw: In this file as well as in the log above I replaced proprietary information as e.g. URL or username by dummy values.

**Comment by jastax** [comment] 2020-03-02 09:19
We (LVM Versicherung) are also experiencing slow startup times with a big Swing-Client. It's not that extreme though (few seconds vs 20-30 seconds) and may not be related to this issue.

(1.1.4)

**Comment by perwah** [comment] 2020-03-26 10:19
Also suffering from this issue with a Spring-based Swing application with component-scan. Takes 3-4 minutes from splash screen to login screen, and log fills up exactly like OP mentioned.

Seems like the problem goes away if using non-signed jars, but that's not really an option.

I get the impression that for every single class that is loaded, the jar is opened, signature-verified, and classpath-attribute removed from the manifest file.

**Comment by AndreasEhret** [comment] 2020-04-09 14:43
please test with 3.0.0-alpha1

**Comment by AG72** [comment] 2020-04-15 10:18
> please test with 3.0.0-alpha1

The version numbers I see is 1.2.0-SNAPSHOT?

**Comment by AG72** [comment] 2020-04-15 10:20
> 
> 
> > please test with 3.0.0-alpha1
> 
> The version numbers I see is 1.2.0-SNAPSHOT?

Ahh, got it : https://github.com/karakun/OpenWebStart/releases/tag/v3.0.0-alpha1

**Comment by AG72** [comment] 2020-04-15 13:15
I tried with 3.0.0a1, but still it takes 4 mintues. The difference to 1.1.1 is that now nothing seems to happen during this time, even no log output on console:
`
2020-04-15 15:07:21,702 [null] [0.0.1.0-SNAPSHOT] [unknown] [15.04.2020 15:03:03] [SwingWorker-pool-4-thread-1] INFO  n.a.i.l.SystemOutLoggerFactory - Wed Apr 15 15:07:21 CEST 2020 [DEBUG  ] com.openwebstart.proxy.direct.DirectProxyProvider: Using NO_PROXY 
2020-04-15 15:07:21,600 [null] [0.0.1.0-SNAPSHOT] [unknown] [15.04.2020 15:03:03] [SwingWorker-pool-4-thread-1] INFO  n.a.i.l.SystemOutLoggerFactory - Wed Apr 15 15:07:21 CEST 2020 [DEBUG  ] com.openwebstart.proxy.direct.DirectProxyProvider: Using NO_PROXY 
2020-04-15 15:03:03,638 [null] [0.0.1.0-SNAPSHOT] [unknown] [15.04.2020 15:03:03] [Application-XXX-thread-1] INFO  de.xxx.yyy.client.SpringLauncher - xxx-swing is running in following env: local-dev
`

**Comment by sclassen** [comment] 2020-04-15 15:55
We need a little more context.
It looks like the time is spent in the application code and not in OWS code.

Could you please clear your log directory and then run your app. Afterwards there should be two or three log files. Please attach them to this issue or send them to openwebstart@karakun.com

**Comment by sclassen** [comment] 2020-04-15 15:56
Also if possible increase verbosity of the application log

**Comment by jastax** [comment] 2020-04-16 08:05
Seems to have cut startup time from 30-40sec to 10-12sec for us. I will test more thoroughly later.

**Comment by jastax** [comment] 2020-04-17 09:17
I've done a few more tests. Sometimes startup time is <10 sec, sometimes nearly a minute.

**Comment by Gr33nbl00d** [comment] 2020-04-22 17:43
We have the same problem, i have to admit we have a quite giant Swing application. 1.5M Lines of Code and  391 Jars to download. The dialog for showing the download progress is also really slow with so many jars. When i maximize it it is simply frozen for minutes only stays white without any repainting.

**Comment by sclassen** [comment] 2020-04-22 17:57
Downloading is done in 6 parallel threads.
Opening more than 6 connections is sometimes punished by servers.
If you have such a large number of dependencies it really pays of to make sure to use the versioned downlad strategy as described in the JSR-56.
If you cannot host a server which supports this download protocoll you can use the workaround described here:
https://docs.oracle.com/javase/tutorial/deployment/deploymentInDepth/avoidingUnnecessaryUpdateChecks.html

**Comment by Gr33nbl00d** [comment] 2020-04-22 18:00
I did some profiling and it seems you have some problem regarding the painting of updates:

See Screenshot below:
https://ibb.co/hstFfc9

Problem seems to be in splashscreen paintcomponent. It has something to do with the text painting

**Comment by sclassen** [comment] 2020-04-22 21:15
The Icedtea Web splash is deactivated.
Could you share your JNLP?
I can currently not see the class `DefaultSplashScreen2012` being used when I run our examples.

**Comment by Gr33nbl00d** [comment] 2020-04-23 18:49
I will do some more analysis in the next days, it seems that the Problem is less heavy with the current snapshot running from ide. It might also only happen if you maximize the progress Window. But i need to do some further analysis

**Comment by hendrikebbers** [comment] 2020-04-24 06:41
The progress window is still one of the IcedTeaWeb pieces that we did not touched until now. And yes, this really needs some refactoring. Sadly we do not have much time for issues like this at the moment.

@sclassen Maybe the spashcreeen code is reused / called in the progress window.

**Comment by hendrikebbers** [comment] 2020-04-24 06:43
I created a new issue about refactoring of the progress window

**Comment by sclassen** [comment] 2020-04-24 11:39
@hendrikebbers 
I started a sample application in the debugger,and my breakpoints were not hit.
Never the less I did a cleanup and opened https://github.com/AdoptOpenJDK/IcedTea-Web/pull/630

**Comment by AG72** [comment] 2020-05-26 13:30
> Also if possible increase verbosity of the application log

I managed to gather more information what happens in the 4 minute gap by installing a development version oft the server. As you will see it is Spring doing things in this time (15:04:01 until 15:08:42) as i.e.:
`[MESSAGE_ALL][Tue May 26 15:04:02 CEST 2020] 2020-05-26 15:04:02,417 [null] [0.0.1.0-SNAPSHOT] [unknown] [26.05.2020 15:04:00] [SwingWorker-pool-4-thread-1] DEBUG o.s.c.a.ClassPathBeanDefinitionScanner - Identified candidate component class: URL [jar:file:/C:/Users/xxx/.cache/icedtea-web/cache/0/28/yyy-swing.jar!/de/ba/zzz/validation/AdresseValidator.class]
`

I'll send the full log by mail.

**Comment by sclassen** [comment] 2020-05-26 14:52
Could be related to https://github.com/spring-projects/spring-framework/issues/9371

**Comment by AG72** [comment] 2020-05-27 09:02
Thanks for this good hint, this may be a solution once we switch to Spring 5.

But the issue you mentioned reports the problem for Oracle Webstart where we do not have any problem. What I still do not understand is that our application with Oracle webstart starts up in a second, while exactly the same application with Openwebstart spents 4 Minutes while Spring does its magic.

**Comment by netopyr** [comment] 2020-05-29 10:32
Hi @AG72 
the problem you describe sounds very specific to your situation and would require more analysis. Unfortunately we do not have the resources to do that right now. But we offer several options of paid support, which may be interesting to you. You can find all the details on our support page: https://openwebstart.com/support/#paid-support-packages

**Comment by FelixJongleur42** [comment] 2020-06-15 13:19
I also have the impression it is the progress dialog UI that is very slow - we have a lot of jars but the connection is fast. Also if the window is opened (pressing the "arrow" in the litte "icon window" on the lower right) - it is much higher than the desktop height, and is "empty" - I have the impression this UI needs to be reworked. Artificial tests should probably try to have a JNLP referencing 200 Jars or so.

**Comment by janakmulani** [comment] 2020-08-14 08:39
@FelixJongleur42 @Th3WalkingDad  @AG72  : Please try OWS 1.2.0 to be released next week. It has changes regarding Downloading Progress Dialogs.

**Comment by Jamila891** [comment] 2020-08-21 07:49
the new version 1.2.0 has been released.

**Comment by Th3WalkingDad** [comment] 2020-08-24 09:47
Here's a feedback for the app loading, both cached and non-cached.
**Launch of CACHED apps in OWS 1.2.1 rocks now**  :-) (see https://board.karakun.com/viewtopic.php?f=21&t=51) !

What I've observed after the initial cache checking (HTTP HEAD for each resource), the **poorly reuse of existing connections**. Indeed half of the resources are loaded on a brand new connection (even if 6 connections "could" be used simultaneously) ... Some connections are only used for 2-4 loads. IMHO, launch of NON-CACHED apps may be little improved, by reusing existing connections.
The greater the latency between client and server (and/or the greater the number of resources to be loaded), the greater the benefit of reusing connection (instead of having the overhead of the 3-ways handshake for each resource). This would be **EVEN MORE TRUE when HTTPS is used**, as further overhead with TLS handshake on top of the connection creation.


This is of course not a blocker but might be important for some people roughly comparing initial loading time with JWS.

As always [YMMV](https://www.urbandictionary.com/define.php?term=ymmv)  (pictures behind links below):
[OWS 1.1.8](https://ibb.co/WBdX1vr) : 44 seconds non-cached on a brand new connections for each ressource.
[OWS 1.2.1](https://ibb.co/mN7VGvS) : 23 seconds non-cached on 6 parallels connections (but 50 to 60 distincts cnx used for 96 jars / 22MB!)
[JWS 8u202](https://ibb.co/h79YJd2) : 16 seconds non-cached on 4 parallels connections (fully re-used)

I haven't quantified the CPU improvement of the download indicator refactoring...

On this "[timeline](https://ibb.co/HdK18Td)" view of the resources loading (independently of the connection used), you can see somehow **"staled" places.**
So explanation is obviously not only connection reuse... that would take nor more than 100ms for me.
I'll maybe take some time this week to profile to possibly get a clue.

**Comment by FelixJongleur42** [comment] 2020-08-24 10:32
Thank you for these great insights!

**Comment by andyedgar** [comment] 2020-08-26 12:15
We are also victims of what appears to be an "over solicitation" of the web start class loader by a spring (v4.3) component scan. Has anyone found a workaround to this problem?

Our application (when version caching is enabled) takes roughly 9 minutes (it doesn't help that our HDs are encrypted).

I have attempted to use 3.0.0.alpha1. However, startup crashes out with a "Could not locate a suitable JRE description in the JNLP file for the underlying execution environment."

As an aside, I'm a bit dense and am trying to understand the OWS roadmap. Is 3.0.0.alpha1 a preview of 1.3.0? If not, where is 2.0.0 on the road map and what kind of timeline (rough) are we looking at for 3.0.0 finalization?

Many thanks for the product!
 Andy

**Comment by janakmulani** [comment] 2020-08-26 13:01
Hi,

>
I have attempted to use 3.0.0.alpha1. However, startup crashes out with a "Could not locate a suitable JRE description in the JNLP file for the underlying execution environment."
>

Can you please send the logs?

3.0.0 is not a preview of OWS 1.3.0. 

3.0.0 is a totally different branch with a new implementation of Classloader. This was done to make Lazy Loading of jars work.  However 3.0.0 branch is still in alpha mode. Please see  [https://openwebstart.com/feature-table/](url)

**Comment by Th3WalkingDad** [comment] 2020-08-26 13:06
Hi @andyedgar 
If you are able to, give a try with non-signed jars (remove MANIFEST.MF from jars).
If it's faster, then maybe try the last answer of this SO thread  ?
https://stackoverflow.com/questions/47095448/spring-component-scan-autowire-in-signed-jar-files-is-slow

**Comment by andyedgar** [comment] 2020-08-27 09:00
Hi @janakmulani. Thanks for your reply

> Can you please send the logs?

Here is the log:
[OWS-3.0.0-alpha1-jvm-error.log](https://github.com/karakun/OpenWebStart/files/5135049/OWS-3.0.0-alpha1-jvm-error.log)

This jnlp's j2se element is as follows:
`<j2se version="11+" vendor="AdoptOpenJDK" initial-heap-size="512m" max-heap-size="1024m"/>`

As @Th3WalkingDad suggested, changing the version from "11+" to "1.8+" circumvented the problem. Now, however, I'm getting the following error:
```
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) 
    at com.sun.glass.ui.Application.lambda$run$1(Application.java:153) 
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(QuantumToolkit.java:258) 
    at com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(QuantumToolkit.java:313) 
    at com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(QuantumToolkit.java:695) 
    at com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(D3DPipeline.java:205) 
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException 
    at java.base/java.lang.Thread.run(Thread.java:834) 
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) 
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) 
    at com.sun.glass.ui.Application.lambda$run$1(Application.java:152) 
    at com.sun.glass.ui.Screen.initScreens(Screen.java:412) 
    at com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method) 
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init> 
    at java.base/java.lang.Thread.run(Thread.java:834) 
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) 
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) 
    at com.sun.glass.ui.Application.lambda$run$1(Application.java:152) 
    at com.sun.glass.ui.Screen.initScreens(Screen.java:412) 
    at com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method) 
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
```

I suspect that this may be coming from the fact that my Oracle Java 8 JRE's dlls are polluting the process:
![image](https://user-images.githubusercontent.com/17085827/91417128-9a2eaf80-e850-11ea-8683-c2580df27ef6.png)
despite the fact that the jnlp file has set the java.library.path property:
`<property name="java.library.path" value="C:/"/>`
This is speculation though, as the error encountered when using v1.2.1 without setting the java.library.path manifests itself differently.

@Th3WalkingDad: thanks for your suggesting concerning spring's context indexer. However, I'm not considering this yet as our spring stack is still on 4.3 and the upgrade will be costly. Nevertheless, I will test with unsigned jars to see if that alleviates the problem. However, it is unfortunate that OWS's (IcedTea-Web) class loader seems to be under performing (by at least an order of magnitude) compared to Java WebStart's. It's unfortunate that Java WebStart's not open source or I'd have a look to see what they're doing differently.

**Comment by sclassen** [comment] 2020-08-27 11:53
The 11+ issue is known and should be fixed with the next 3.0.0 release.
For the rest I am currently too far away to be able to give a quick response

**Comment by sclassen** [comment] 2020-10-02 08:11
Did you see any performance improvements with version 1.2.1 ??

**Comment by sclassen** [comment] 2020-10-02 21:49
I close this issue now as 1.2.1 has brought great improvements.
For the re-use of HTTP connections I created a new issue in ITW (https://github.com/AdoptOpenJDK/IcedTea-Web/issues/709)

If there are other performance issues still remaining please open a new issue either with OWS or ITW.

**Closed by sclassen** 2020-10-02 21:49 UTC
Labels: tracked internally

**Comment by AG72** [comment] 2021-01-25 13:27
> Could be related to [spring-projects/spring-framework#9371](https://github.com/spring-projects/spring-framework/issues/9371)

To add a last note: Using OWS 1.3.1 and finally updating our project to Spring 5 brought the solution: The bean scanning index improves the startup time from 4 minutes to a few seconds!

**Comment by in-fke** [comment] 2022-12-01 00:56
I took the freedom to open another discussion, opening and verifying all those jar files, "just" to modify the `Class-Path` attribute!?
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/889
