### ISSUE TITLE
none jndi.xxx properties are not passed to runtime any more with 1.10.0

### ISSUE THREAD

**Issue by markuslutumnedap** [karakun/OpenWebStart#588] opened 2024-06-06 06:12 UTC
We use very complex JNLP files with a huge set of properties like:
`<property name="myprefix.initialContextFactory" value="org.wildfly.naming.client.WildFlyInitialContextFactory"/>`
In the past we had an issue using the default jndi.xxx prefix because the generated -Djndi.xxx commandline was too long.
So we changed to lets say myprefix.xxx
Since 1.10.0 those are not added any more.

The workaround using deployment.properties mentioned here:
https://board.karakun.com/viewtopic.php?p=10573&sid=072e283934096c0d1e95f20de055344e#p10573
is not applicable. The client machine is not under our control. The jnlp file change and there are a lot of properties used.

This breaks the applications currently when the clients press update OWS on startup.

**Comment by fleminra** [comment] 2024-06-07 05:22
Probably a duplicate of https://github.com/karakun/OpenWebStart/issues/587.

**Comment by markuslutumnedap** [comment] 2024-06-07 06:30
I agree...  can be closed as duplicate

**Comment by sclassen** [comment] 2024-06-07 21:54
We found the source of the problem an plan on releasing a bugfix early next week

**Comment by sclassen** [comment] 2024-06-14 08:07
Fixed with [1.10.1](https://github.com/karakun/OpenWebStart/releases/tag/v1.10.1)

**Closed by sclassen** 2024-06-14 08:07 UTC
